version: '2'

services:
  ext:
    image: hyperledger/fabric-tools:${FABRIC_IMAGE_TAG}
    container_name: ov_ext
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - GOPATH=/opt/gopath
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_LOGGING_LEVEL=info
      - CHANNEL_NAME=mychannel
      - CHANNEL_JOIN_COUNTER=1
      - CHANNEL_JOIN_MAX_RETRY=5
      - CC_TEST=${CC_TEST}
      - CC_LANGUAGE=golang
      - CC_QUERY_TIMEOUT=10
    working_dir: /etc/hyperledger/fabric/scripts
    command: '/bin/bash main.sh'
    volumes:
      - ./scripts:/etc/hyperledger/fabric/scripts
      - ./chaincode:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/etc/hyperledger/fabric/crypto-config
      - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts