version: '3'

networks:
  existing_overlay_network:
    external:
      name: ${COMPOSE_PROJECT_NAME}_${NETWORK_NAME}

services:
  update:
    deploy:
      replicas: 1
      restart_policy:
        condition: none
        delay: 10s
        max_attempts: 1
        window: 1000s
      placement:
        constraints:
          - node.hostname == manager
    image: hyperledger/fabric-tools:${FABRIC_IMAGE_TAG}
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - GOPATH=/opt/gopath
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CHANNEL_CREATE_TIMEOUT=20
      - CHANNEL_NAME=${CHANNEL_NAME}
      - CORE_LOGGING_LEVEL=${LOG_LEVEL}
      - CORE_PEER_ID=cli
      - CORE_PEER_TLS_ENABLED=true
    # crypto-config.yaml
    working_dir: /etc/hyperledger/fabric
    command: '/bin/bash main.sh'
    volumes:
      - ./main.sh:/etc/hyperledger/fabric/main.sh
      - ~/fabric/crypto-config:/etc/hyperledger/fabric/crypto-config
      - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
    networks:
      - existing_overlay_network