  ca_{{ZJHL_DOMAIN}}:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.hostname == {{MACHINE_NAME}}
    # image 默认 tag 是 lastest
    image: hyperledger/fabric-ca:${FABRIC_IMAGE_TAG}
    environment:
      # 公私钥存放目录
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=ca_{{ZJHL_DOMAIN}}
      - FABRIC_CA_SERVER_TLS_KEYFILE=/var/ca-config/${ZJHL_CA_KEYFILE}
      - FABRIC_CA_SERVER_TLS_CERTFILE=/var/ca-config/ca.{{ZJHL_DOMAIN}}.com-cert.pem
    # command 中引用 environment ，需要用 $$
    command: sh -c "fabric-ca-server start --ca.certfile $${FABRIC_CA_SERVER_TLS_CERTFILE} --ca.keyfile $${FABRIC_CA_SERVER_TLS_KEYFILE} -b admin:adminpw -d"
    volumes:
      - {{ZJHL_DOMAIN}}_ca_volume:/var/ca-config:readonly
    ports:
      - "{{(INDEX*10+7054)}}:7054"
    networks:
      existing_overlay_network:
        aliases:
          - ca.{{ZJHL_DOMAIN}}.com