version: '2'

services:
  add:
    image: hyperledger/fabric-tools:${FABRIC_IMAGE_TAG}
    container_name: ov_add
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - GOPATH=/opt/gopath
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_LOGGING_LEVEL=${LOG_LEVEL}
      - CORE_PEER_ID=cli
      - CORE_PEER_TLS_ENABLED=true
      - STEP_NUMBER=${STEP_NUMBER}

      - CHANNEL_NAME=${CHANNEL_NAME}
      - CHANNEL_CREATE_TIMEOUT=20
      - CHANNEL_JOIN_COUNTER=1
      - CHANNEL_JOIN_MAX_RETRY=5
      - CC_TEST=${CC_TEST}
      - CC_LANGUAGE=golang
      - CC_QUERY_TIMEOUT=10
    working_dir: /etc/hyperledger/fabric/scripts
    command: '/bin/bash main.sh'
    volumes:
      - ./crypto-config.yaml:/etc/hyperledger/fabric/crypto-config.yaml
      - ./configtx.yaml:/etc/hyperledger/fabric/configtx.yaml
      - ./crypto-config:/etc/hyperledger/fabric/crypto-config
      - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - ./scripts:/etc/hyperledger/fabric/scripts
      - ./chaincode:/opt/gopath/src/github.com/chaincode